---

# https://github.com/heketi/heketi/blob/master/docs/admin/install-standalone.md

- name: "Install Heketi API"
  debug:
    msg: "Install Heketi API"

# install
# wget https://github.com/heketi/heketi/releases/download/1.0.1/heketi-1.0.1.linux.amd64.tar.gz
# tar xzvf heketi-1.0.1.linux.amd64.tar.gz
# cd heketi
# ./heketi -version
# Heketi v1.0.1

- name: "Install heketi"
  unarchive:
    src: https://github.com/heketi/heketi/releases/download/1.0.1/heketi-1.0.1.linux.amd64.tar.gz
    dest: /tmp
    remote_src: yes

- name: Copy Heketi binaries
  shell: "cp /tmp/heketi/heketi* /usr/bin"
  args:
    creates: /usr/bin/heketi

- name: "Copy heketi conf"
  template:
    src: heketi.json
    dest: /etc/heketi.json

# https://github.com/heketi/heketi/blob/master/docs/admin/server.md

# launch
# heketi --config=<config file>

- debug:
    msg: "heketi --config=/etc/heketi.json"