---
# tasks file for glusterfs
# https://www.howtoforge.com/creating-an-nfs-like-standalone-storage-server-with-glusterfs-3.2.x-on-ubuntu-12.10

- name: "Install GlusterFs server"
  debug:
    msg: "Install GlusterFs server"

- name: "Update /etc/hosts"
  lineinfile:
    path: /etc/hosts
    line: "{{ item }}"
  with_items:
    - "192.168.99.50   ubuntu-data"
    - "192.168.33.50   ubuntu-data"

- name: Install GlusterFs
  package:
    name: "{{item}}"
  with_items:
    - glusterfs-server
    - glusterfs-client

- name: "Create directories"
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "/mnt/glusterfs"
    - /data
    - /data/brick1

- name: Format /dev/sdf
  filesystem:
    fstype: xfs
    dev: /dev/sdf

- name: "Update fstab"
  lineinfile:
    path: /etc/fstab
    line: "/dev/sdf /data xfs defaults 1 2"

# gluster volume create testvol 192.168.99.50:/data
# gluster volume start testvol
- name: "Create glusterfs volume"
  shell: |
    gluster volume create testvol 192.168.99.50:/data/brick1
    gluster volume start testvol
    touch /root/glusterfs-volume-testvol
  args:
    creates: /root/glusterfs-volume-testvol

# gluster volume info
- command: gluster volume info
  register: gluster_volume_info

- debug:
    msg: "{{ gluster_volume_info.stdout }}"

# Glusterfs Client

# mount.glusterfs ubuntu-data:/testvol /mnt/glusterfs

- name: "Mount Glusterfs"
  mount:
    path: /mnt/cephfs
    src: "192.168.99.50:/testvol"
    fstype: glusterfs
    state: present
