---

- debug:
    msg: "X11 OpenBSD"

- name: Install dependencies
  openbsd_pkg:
    name: [
      xfce,
      slim
    ]
    state: present

#  export PKG_PATH=https://ftp.openbsd.org/pub/OpenBSD/6.4/packages/amd64/

- name: "Enable startx"
  lineinfile:
    path: /home/vagrant/.xinitrc
    line: exec startxfce4
    owner: vagrant
    group: vagrant
    create: yes

- name: "Enable slim"
  lineinfile:
    path: /etc/rc.local
    line: /usr/local/bin/slim -d
    create: yes

- name: "Enable dbus"
  lineinfile:
    path: /etc/rc.conf.local
    line: "{{ item }}"
  with_items:
    - 'pkg_scripts="dbus_daemon avahi_daemon"'
    - 'dbus_enable=YES'

# /usr/X11R6/share/X11/xorg.conf.d/keyboard-fr-mac.conf
- name: "Keyboard fr mac"
  template:
    src: keyboard-fr-mac.conf
    dest: /usr/X11R6/share/X11/xorg.conf.d/keyboard-fr-mac.conf