apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
        privateKey: /etc/istio/ingressgateway-certs/tls.key
      hosts:
        - "*"

---

#apiVersion: networking.istio.io/v1alpha3
#kind: Gateway
#metadata:
#  name: dashboard
#  namespace: istio-system
#spec:
#  selector:
#    istio: ingressgateway
#  servers:
#    - port:
#        number: 443
#        name: https-dashboard
#        protocol: HTTPS
#      tls:
#        mode: PASSTHROUGH
#      hosts:
#        - dashboard.192.168.33.16.nip.io

---

#apiVersion: networking.istio.io/v1alpha3
#kind: VirtualService
#metadata:
#  name: dashboard
#  namespace: istio-system
#spec:
#  hosts:
#    - "dashboard.192.168.33.16.nip.io"
#  gateways:
#    - istio-gateway
#  http:
#    - match:
#        - uri:
#            prefix: /
#      route:
#        - destination:
#            host: kubernetes-dashboard
#            port:
#              number: 443

#---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: grafana
  namespace: istio-system
spec:
  hosts:
    - "grafana.192.168.33.16.nip.io"
  gateways:
    - istio-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: grafana
            port:
              number: 3000

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: prometheus
  namespace: istio-system
spec:
  hosts:
    - "prometheus.192.168.33.16.nip.io"
  gateways:
    - istio-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: prometheus
            port:
              number: 9090

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: jaeger
  namespace: istio-system
spec:
  hosts:
    - "jaeger.192.168.33.16.nip.io"
  gateways:
    - istio-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: jaeger-query
            port:
              number: 16686
---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: servicegraph
  namespace: istio-system
spec:
  hosts:
    - "servicegraph.192.168.33.16.nip.io"
  gateways:
    - istio-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: servicegraph
            port:
              number: 8088

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: zipkin
  namespace: istio-system
spec:
  hosts:
    - "zipkin.192.168.33.16.nip.io"
  gateways:
    - istio-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: zipkin
            port:
              number: 9411

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kiali
  namespace: istio-system
spec:
  hosts:
    - "kiali.192.168.33.16.nip.io"
  gateways:
    - istio-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: kiali
            port:
              number: 20001