
---
- hosts: data-servers
  remote_user: root
  vars:
    host: 192.168.0.0/16
    server_share_dir: /var/nfs
    client_share_dir: /mnt/nfs
    ceph_disks:
      - sde
      - sdf
      - sdd
  roles:
    #- common
    #- nfs
    #- ceph
    - glusterfs
  become: yes